//
//  UMDBuildings.swift
//  beaconclaude
//
//  University of Maryland campus buildings list
//

import Foundation

struct UMDBuildings {
    static let buildings = [
        "I have it",
        "Adele H. Stamp Student Union",
        "Administration Building",
        "Agriculture Building",
        "Armory",
        "Art-Sociology Building",
        "Atlantic Building",
        "Avrum Gudelsky Veterinary Center",
        "Benjamin Building",
        "Biosciences Research Building",
        "Brendan Iribe Center",
        "Cambridge Community Center",
        "Campus Recreation Center",
        "Centreville Hall",
        "Chesapeake Building",
        "Chemistry Building",
        "Clarice Smith Performing Arts Center",
        "Cole Student Activities Building",
        "Computer Science Instructional Center",
        "Cumberland Hall",
        "Denton Hall",
        "Dorchester Hall",
        "Edward St. John Learning and Teaching Center",
        "Ellicott Hall",
        "Eppley Recreation Center",
        "Francis Scott Key Hall",
        "Glenn L. Martin Hall",
        "H.J. Patterson Hall",
        "Hagerstown Hall",
        "Holzapfel Hall",
        "Hornbake Library",
        "Jeong H. Kim Engineering Building",
        "Jull Hall",
        "Keystone Apartments",
        "La Plata Hall",
        "LaVale Hall",
        "LeFrak Hall",
        "Marie Mount Hall",
        "Martin Hall",
        "Mathematics Building",
        "McKeldin Library",
        "McMahon Hall",
        "Mitchell Building",
        "Morrill Hall",
        "North Campus Dining Hall",
        "Oakland Hall",
        "Physical Sciences Complex",
        "Plant Sciences Building",
        "Potomac Building",
        "Prince Frederick Hall",
        "Riverdale Park",
        "Rossborough Inn",
        "Samuel Riggs IV Alumni Center",
        "Shoemaker Building",
        "Skinner Building",
        "South Campus Commons",
        "South Campus Dining Hall",
        "Stamp Student Union",
        "Susquehanna Hall",
        "Symons Hall",
        "Taliaferro Hall",
        "The Armory",
        "Tawes Hall",
        "Tydings Hall",
        "Van Munching Hall",
        "Walter Hill",
        "Wicomico Hall",
        "William E. Kirwan Hall",
        "Woods Hall",
        "Xfinity Center"
    ].sorted()
}

